export const MAX_FISH_TYPES = 25;
export const MAX_EXPENSE_CATEGORIES = 20;
export const MAX_EMPLOYEE_CATEGORIES = 5;
export const MAX_CUSTOMERS = 1000;
export const MAX_SUPPLIERS = 500;

export const MAX_NAME_LENGTH = 40;
export const MAX_PHONE_LENGTH = 15;
export const MAX_ADDRESS_LENGTH = 150;
export const MAX_NOTES_LENGTH = 200;

export const LIMITS = {
  MAX_FISH_TYPES,
  MAX_EXPENSE_CATEGORIES,
  MAX_EMPLOYEE_CATEGORIES,
  MAX_CUSTOMERS,
  MAX_SUPPLIERS,
  MAX_NAME_LENGTH,
  MAX_PHONE_LENGTH,
  MAX_ADDRESS_LENGTH,
  MAX_NOTES_LENGTH
};

export default LIMITS;
